name: Packer Checks

on:
  pull_request:
    branches:
      - main

jobs:
  packer-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Building the Artifacts
        run: zip -r webapp.zip ./

      - name: Install Packer
        run: |
          curl -fsSL https://releases.hashicorp.com/packer/1.7.0/packer_1.7.0_linux_amd64.zip -o packer.zip
          unzip packer.zip
          sudo mv packer /usr/local/bin/
          packer --version

      - name: Initialize Packer
        run: packer init packer.pkr.hcl

      - name: Format Packer Template
        run: packer fmt -check packer.pkr.hcl

      - name: Validate Packer Template
        run: packer validate packer.pkr.hcl

  # Integration Tests
  integration-test:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Dependencies
        run: npm install

      - name: Run Integration Tests
        run: npm test

  # Build & Deploy AMI + GCP Image
  build:
    runs-on: ubuntu-latest
    needs: integration-test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Building the Artifacts (Including `tests` Folder)
        run: |
          mkdir -p build
          cp app.js package.json package-lock.json -r tests build/
          zip -r webapp.zip build/

      - name: Install Packer
        run: |
          curl -fsSL https://releases.hashicorp.com/packer/1.7.0/packer_1.7.0_linux_amd64.zip -o packer.zip
          unzip packer.zip
          sudo mv packer /usr/local/bin/
          packer --version

      - name: Initialize Packer
        run: packer init packer.pkr.hcl

      - name: Authenticate with AWS
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: aws sts get-caller-identity

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Validate Packer Template
        run: packer validate packer.pkr.hcl

      - name: Build Packer Images for AWS & GCP
        run: |
          packer build packer.pkr.hcl
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
