# name: Packer Format & Validate

# on:
#   pull_request:
#     branches:
#       - main

# jobs:
#   packer-validation:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v4

#       - name: Setup Packer
#         uses: hashicorp/setup-packer@v1

#       - name: Check Packer Formatting
#         run: packer fmt -check packer.pkr.hcl

#       - name: Validate Packer Template
#         run: packer validate packer.pkr.hcl

name: Packer CI & Build

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

jobs:
  packer-format-validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Packer
        uses: hashicorp/setup-packer@v2
        with:
          version: latest

      - name: Run Packer Format
        run: packer fmt -check packer.pkr.hcl

      - name: Validate Packer Template
        run: packer validate packer.pkr.hcl

  packer-build:
    needs: packer-format-validate # Ensures validation passes before building
    if: github.event_name == 'push' # Only runs on push (not PR)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install Packer
        uses: hashicorp/setup-packer@v2
        with:
          version: latest

      - name: Build AMI with Packer
        run: packer build packer.pkr.hcl
