# name: Packer Format & Validate

# on:
#   pull_request:
#     branches:
#       - main

# jobs:
#   packer-validation:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v4

#       - name: Setup Packer
#         uses: hashicorp/setup-packer@v1

#       - name: Check Packer Formatting
#         run: packer fmt -check packer.pkr.hcl

#       - name: Validate Packer Template
#         run: packer validate packer.pkr.hcl

#

name: Packer CI & Build

on:
  pull_request:
    branches:
      - main # ✅ Runs validation when a PR is created

  push:
    branches:
      - main # ✅ Runs AMI build when PR is merged

jobs:
  integration-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Integration Tests
        run: |
          npm install
          npm test # ✅ Adjust this based on your framework

  build-artifact:
    needs: integration-test # ✅ Runs only if integration tests pass
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Application Artifact
        run: |
          mkdir -p /tmp/artifacts
          npm install
          npm run build # ✅ Adjust based on your build process
          cp -r build/* /tmp/artifacts/

      - name: Upload Artifacts for Packer Build
        uses: actions/upload-artifact@v3
        with:
          name: webapp-artifacts
          path: /tmp/artifacts/

  packer-format-validate:
    needs: build-artifact
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Packer
        uses: hashicorp/setup-packer@v2
        with:
          version: latest

      - name: Initialize Packer Plugins
        run: packer init .

      - name: Run Packer Format
        run: packer fmt -check packer.pkr.hcl

      - name: Validate Packer Template
        run: packer validate packer.pkr.hcl

  packer-build:
    needs: packer-format-validate
    if: github.event_name == 'push' # ✅ Runs only after PR is merged
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install Packer
        uses: hashicorp/setup-packer@v2
        with:
          version: latest

      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: webapp-artifacts
          path: /tmp/artifacts/

      - name: Initialize Packer Plugins
        run: packer init .

      - name: Build AMI with Packer
        run: packer build packer.pkr.hcl
