name: Packer AWS CI/CD Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  # Packer Validation Job (Runs on PR)
  packer-check:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Packer
        run: |
          curl -fsSL https://releases.hashicorp.com/packer/1.7.0/packer_1.7.0_linux_amd64.zip -o packer.zip
          unzip packer.zip
          sudo mv packer /usr/local/bin/
          packer --version

      - name: Format Packer Template
        run: packer fmt packer.pkr.hcl
        continue-on-error: false

      - name: Validate Packer Template
        run: packer validate packer.pkr.hcl

  # Integration Tests (Runs on Merge)
  integration-test:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Dependencies
        run: npm install

      - name: Run Integration Tests
        run: npm test

  # Build & Deploy AMI
  build:
    runs-on: ubuntu-latest
    needs: integration-test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Building the Artifacts (Including `tests` Folder)
        run: |
          mkdir -p build
          cp app.js package.json package-lock.json setup_application.sh -r tests build/
          zip -r webapp.zip build/

      - name: Install Packer
        run: |
          curl -fsSL https://releases.hashicorp.com/packer/1.7.0/packer_1.7.0_linux_amd64.zip -o packer.zip
          unzip packer.zip
          sudo mv packer /usr/local/bin/
          packer --version

      - name: Initialize Packer
        run: packer init packer.pkr.hcl

      - name: Validate Packer Template
        run: packer validate packer.pkr.hcl

      - name: Build Packer Image
        run: packer build -var "app_archive=webapp.zip" packer.pkr.hcl
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
